import { MODEL_FACTORY, MODEL_SCALE } from '@/constants/factory';
import { IFactoryItem } from '@/types/MapBoxTypes';

const TheNorthFactory: readonly IFactoryItem[] = [
  {
    id: 'factory-thang-long',
    name: 'Thang Long Industrial Park',
    coordinates: [105.7427, 21.0172, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Dong Anh District, Hanoi',
    phone: '024 3883 5990',
    status: 'available',
    patients: 1250,
    city: 'Hanoi',
  },
  {
    id: 'factory-canon',
    name: 'Canon Vietnam Factory',
    coordinates: [105.9335, 21.0128, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Que Vo Industrial Zone, Bac Ninh',
    phone: '024 3722 0001',
    status: 'full',
    patients: 1500,
    city: 'Hanoi',
  },
  {
    id: 'factory-honda',
    name: 'Honda Vietnam Factory',
    coordinates: [105.7676, 21.0674, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Phuc Thang Ward, Phuc Yen Town, Vinh Phuc',
    phone: '024 6255 6556',
    status: 'available',
    patients: 980,
    city: 'Hanoi',
  },
  {
    id: 'factory-yamaha',
    name: 'Yamaha Motor Vietnam',
    coordinates: [106.041, 20.8741, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Hanoi-Hai Phong Road, Hung Yen',
    phone: '024 3974 5556',
    status: 'available',
    patients: 750,
    city: 'Hanoi',
  },
  {
    id: 'factory-industrial-noi-bai',
    name: 'Noi Bai Industrial Zone',
    coordinates: [105.8106, 21.2171, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Soc Son District, Hanoi',
    phone: '024 3583 5226',
    status: 'full',
    patients: 1100,
    city: 'Hanoi',
  },
  {
    id: 'factory-panasonic',
    name: 'Panasonic Vietnam',
    coordinates: [105.774, 20.9978, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Thang Long Industrial Park, Dong Anh, Hanoi',
    phone: '024 3974 4460',
    status: 'available',
    patients: 620,
    city: 'Hanoi',
  },
  {
    id: 'factory-habeco',
    name: 'Hanoi Beer Company',
    coordinates: [105.842, 21.0149, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: '183 Hoang Hoa Tham Street, Ba Dinh District, Hanoi',
    phone: '024 3845 5529',
    status: 'available',
    patients: 800,
    city: 'Hanoi',
  },
  {
    id: 'factory-samsung-electronics',
    name: 'Samsung Electronics Vietnam',
    coordinates: [105.9113, 21.1392, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Yen Phong Industrial Zone, Bac Ninh',
    phone: '024 3850 7342',
    status: 'full',
    patients: 450,
    city: 'Hanoi',
  },
  {
    id: 'factory-bac-thang-long',
    name: 'North Thang Long Industrial Zone',
    coordinates: [105.7739, 21.1038, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Dong Anh District, Hanoi',
    phone: '024 3882 1038',
    status: 'available',
    patients: 890,
    city: 'Hanoi',
  },
  {
    id: 'factory-phu-nghia',
    name: 'Phu Nghia Industrial Zone',
    coordinates: [105.6536, 20.9226, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Chuong My District, Hanoi',
    phone: '024 3345 0198',
    status: 'full',
    patients: 1300,
    city: 'Hanoi',
  },
  {
    id: 'factory-ford-vietnam',
    name: 'Ford Vietnam Factory',
    coordinates: [106.165, 20.9626, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Hai Duong Province',
    phone: '024 3826 4624',
    status: 'available',
    patients: 750,
    city: 'Hanoi',
  },
  {
    id: 'factory-garment-10',
    name: 'Garment 10 Corporation',
    coordinates: [105.7904, 21.0287, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Sai Dong B Industrial Zone, Long Bien District, Hanoi',
    phone: '024 3826 0440',
    status: 'available',
    patients: 620,
    city: 'Hanoi',
  },
  {
    id: 'factory-cp-vietnam',
    name: 'CP Vietnam Corporation',
    coordinates: [105.9197, 21.071, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Bien Hoa Industrial Zone, Ha Noi',
    phone: '024 3928 6665',
    status: 'full',
    patients: 450,
    city: 'Hanoi',
  },
  {
    id: 'factory-quang-minh',
    name: 'Quang Minh Industrial Zone',
    coordinates: [105.7476, 21.1501, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Me Linh District, Hanoi',
    phone: '024 3813 9731',
    status: 'available',
    patients: 850,
    city: 'Hanoi',
  },
  {
    id: 'factory-vinacomin',
    name: 'Vinacomin - Vietnam Coal Corporation',
    coordinates: [105.849, 21.0137, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: '226 Le Duan Street, Dong Da District, Hanoi',
    phone: '024 3851 0780',
    status: 'full',
    patients: 1200,
    city: 'Hanoi',
  },
  {
    id: 'factory-dai-tu-steel',
    name: 'Dai Tu Steel Factory',
    coordinates: [105.7852, 21.0447, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Dai Tu District, Thai Nguyen Province',
    phone: '024 3786 4912',
    status: 'available',
    patients: 680,
    city: 'Hanoi',
  },
  {
    id: 'factory-toyota-vietnam',
    name: 'Toyota Motor Vietnam',
    coordinates: [105.9617, 21.0728, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Phuc Yen District, Vinh Phuc Province',
    phone: '024 3868 9901',
    status: 'available',
    patients: 550,
    city: 'Hanoi',
  },
  {
    id: 'factory-dong-anh-electronics',
    name: 'Dong Anh Electronics Factory',
    coordinates: [105.8325, 21.1366, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Dong Anh District, Hanoi',
    phone: '024 3883 2671',
    status: 'available',
    patients: 420,
    city: 'Hanoi',
  },
  {
    id: 'factory-tien-son',
    name: 'Tien Son Industrial Zone',
    coordinates: [106.0771, 21.1043, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Tien Du District, Bac Ninh Province',
    phone: '0222 3843 215',
    status: 'available',
    patients: 780,
    city: 'Bac Ninh',
  },
  {
    id: 'factory-que-vo',
    name: 'Que Vo Industrial Zone',
    coordinates: [106.1862, 21.1492, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Que Vo District, Bac Ninh Province',
    phone: '0222 3634 034',
    status: 'full',
    patients: 950,
    city: 'Bac Ninh',
  },
  {
    id: 'factory-yen-phong',
    name: 'Yen Phong Industrial Zone',
    coordinates: [105.9599, 21.2019, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Yen Phong District, Bac Ninh Province',
    phone: '0222 3899 117',
    status: 'available',
    patients: 1150,
    city: 'Bac Ninh',
  },
];

const CentralRegionFactory: readonly IFactoryItem[] = [
  {
    id: 'factory-hoa-khanh',
    name: 'Hoa Khanh Industrial Zone',
    coordinates: [108.1608, 16.0651, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Lien Chieu District, Da Nang City',
    phone: '0236 3841 121',
    status: 'available',
    patients: 890,
    city: 'Da Nang',
  },
  {
    id: 'factory-lien-chieu',
    name: 'Lien Chieu Industrial Zone',
    coordinates: [108.1334, 16.0907, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Lien Chieu District, Da Nang City',
    phone: '0236 3797 255',
    status: 'full',
    patients: 670,
    city: 'Da Nang',
  },
  {
    id: 'factory-danang-seafood',
    name: 'Da Nang Seafood Processing Factory',
    coordinates: [108.2001, 16.0729, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Son Tra District, Da Nang City',
    phone: '0236 3921 221',
    status: 'available',
    patients: 450,
    city: 'Da Nang',
  },
  {
    id: 'factory-danang-rubber',
    name: 'Da Nang Rubber Company',
    coordinates: [108.1726, 16.0467, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Hoa Khanh Industrial Zone, Da Nang City',
    phone: '0236 3847 256',
    status: 'available',
    patients: 520,
    city: 'Da Nang',
  },
  {
    id: 'factory-hoa-cam',
    name: 'Hoa Cam Industrial Zone',
    coordinates: [108.1872, 16.0111, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Cam Le District, Da Nang City',
    phone: '0236 3846 126',
    status: 'full',
    patients: 380,
    city: 'Da Nang',
  },
];

const TheSouthFactory: readonly IFactoryItem[] = [
  {
    id: 'factory-tan-thuan',
    name: 'Tan Thuan Export Processing Zone',
    coordinates: [106.7238, 10.7449, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'District 7, Ho Chi Minh City',
    phone: '028 3770 0999',
    status: 'available',
    patients: 1600,
    city: 'Ho Chi Minh City',
  },
  {
    id: 'factory-tan-binh',
    name: 'Tan Binh Industrial Park',
    coordinates: [106.6434, 10.8034, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Tan Binh District, Ho Chi Minh City',
    phone: '028 3816 0040',
    status: 'full',
    patients: 1200,
    city: 'Ho Chi Minh City',
  },
  {
    id: 'factory-vissan',
    name: 'Vissan Food Processing Factory',
    coordinates: [106.6402, 10.7616, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Binh Thanh District, Ho Chi Minh City',
    phone: '028 3553 3999',
    status: 'available',
    patients: 950,
    city: 'Ho Chi Minh City',
  },
  {
    id: 'factory-saigon-beer',
    name: 'Saigon Beer Factory',
    coordinates: [106.7157, 10.7506, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'District 1, Ho Chi Minh City',
    phone: '028 3822 8885',
    status: 'full',
    patients: 1100,
    city: 'Ho Chi Minh City',
  },
  {
    id: 'factory-hiep-phuoc',
    name: 'Hiep Phuoc Industrial Park',
    coordinates: [106.7688, 10.6682, 0],
    modelPath: MODEL_FACTORY,
    scale: MODEL_SCALE,
    address: 'Nha Be District, Ho Chi Minh City',
    phone: '028 3780 0345',
    status: 'available',
    patients: 850,
    city: 'Ho Chi Minh City',
  },
];

export const ListFactoryModels: readonly IFactoryItem[] = [
  ...TheNorthFactory,
  ...CentralRegionFactory,
  ...TheSouthFactory,
];
